### ISSUE TITLE
Review Understanding Core Concepts

### ISSUE THREAD

**Issue by watrall** [chi-initiative/kora-documentation#32]
Review Understanding Field Types

https://chi-initiative.github.io/kora-documentation/forms/understanding_field_types/

Check for (1) clarity, (2) accuracy, (3) and grammar/composition (spelling, etc).

**Comment by geyerbri** [comment]
This issue appears twice and there's no issue for "Understanding Core Concepts", so I'm coopting this one for that (because I reviewed "Understanding Core Concepts")

**Comment by geyerbri** [comment]
done
