### ISSUE TITLE
Create Contributing to this Documentation page 

### ISSUE THREAD

**Issue by watrall** [chi-initiative/kora-documentation#37]
Create a "Contributing to this Documentation" page.  
- Put under "Getting Started" section
- Geared towards people who have minimal familiarity with Github (similar to the target audience for the "Installing on Reclaim" tutorial.  
- Geared towards someone who isn't part of the CHI organization (so, whole pull request process should be documented)  
- Step by step, no assumptions made, screenshots, descriptive (not just what they need to do, but why they are doing it.

**Comment by geyerbri** [comment]
This was finished on 16 August
