### ISSUE TITLE
Implement guilabel

### ISSUE THREAD

**Issue by watrall** [chi-initiative/kora-documentation#43]
Implement guilabel.  As with #40 , might require v2 config file.

**Comment by geyerbri** [comment]
As far as I can tell, using :guilabel: and other text roles requires [transitioning to .rst files](https://www.sphinx-doc.org/en/master/usage/restructuredtext/index.html) for everything. I can't find a singe example of it in mkdocs, and the readthedocs examples are all in .rst files.

And transitioning to .rst would mean leaving behind mkdocs: see  mkdocs/mkdocs#1817.

So to come up with an alternative, how were you intending us to use :guilabel:? And did you only want this, or was this a reference to [all kinds of text roles](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html) (e.g. :file:, :doc:, :download:, :guilabel:, etc.)?

**Comment by watrall** [comment]
sounds good.  I'm unwilling to make this change in order to get :guilabel
